<script type="text/javascript" src="/perch/addons/plugins/editors/custom_tinymce/tinymce/jquery.tinymce.min.js"></script>
<script src="PERCH_LOGINPATH/addons/plugins/editors/custom_tinymce/scripts/upload.js"></script>
<script src="PERCH_LOGINPATH/addons/plugins/editors/custom_tinymce/scripts/button.js"></script>
<script src="PERCH_LOGINPATH/addons/plugins/editors/custom_tinymce/scripts/textarea.js"></script>
<script src="PERCH_LOGINPATH/addons/plugins/editors/custom_tinymce/scripts/main.js"></script>
<script src="PERCH_LOGINPATH/core/assets/js/jquery.form.min.js"></script>
<link rel="stylesheet" href="PERCH_LOGINPATH/addons/plugins/editors/custom_tinymce/styles/custom_tinymce.css" />