<script type="text/javascript" src="/perch/addons/plugins/editors/custom_tinymce/tinymce/jquery.tinymce.min.js"></script>
<script src="PERCH_LOGINPATH/addons/plugins/editors/custom_tinymce/config.js"></script>
<script src="PERCH_LOGINPATH/addons/plugins/editors/custom_tinymce/image_upload/image_upload.js"></script>
<script src="PERCH_LOGINPATH/core/assets/js/jquery.form.min.js"></script>
<link rel="stylesheet" href="PERCH_LOGINPATH/addons/plugins/editors/markitup/css/markitup.min.css" />